import type { Metadata } from "next";

import "../globals.css";
import { Footer, Header, Navigation } from "../_components";

export const metadata: Metadata = {
  title: "Studio Quickstart",
  description: "Generated by the Contentful Team!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Navigation />
        <main className="container p-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
